extends Node
class_name SkillData
## Database of all skills. BDO-inspired with cooldowns, AoE, and mana costs.

const SKILLS := {
	# === WARRIOR SKILLS ===
	"slash": {
		"name": "Slash",
		"description": "A powerful forward slash.",
		"class": ClassData.ClassType.WARRIOR,
		"damage_multiplier": 1.5,
		"mana_cost": 5,
		"cooldown": 0.8,
		"range": 40.0,
		"aoe_radius": 0.0,
		"hits": 1,
		"hotkey": "skill_1",
		"icon_color": Color(1, 0.5, 0.2),
	},
	"whirlwind": {
		"name": "Whirlwind",
		"description": "Spin attack hitting all nearby enemies.",
		"class": ClassData.ClassType.WARRIOR,
		"damage_multiplier": 1.2,
		"mana_cost": 15,
		"cooldown": 4.0,
		"range": 60.0,
		"aoe_radius": 60.0,
		"hits": 3,
		"hotkey": "skill_2",
		"icon_color": Color(1, 0.3, 0.1),
	},
	"shield_charge": {
		"name": "Shield Charge",
		"description": "Charge forward, knocking back enemies.",
		"class": ClassData.ClassType.WARRIOR,
		"damage_multiplier": 2.0,
		"mana_cost": 20,
		"cooldown": 8.0,
		"range": 80.0,
		"aoe_radius": 30.0,
		"hits": 1,
		"hotkey": "skill_3",
		"icon_color": Color(0.8, 0.7, 0.2),
	},
	"ground_slam": {
		"name": "Ground Slam",
		"description": "Slam the ground for massive AoE damage.",
		"class": ClassData.ClassType.WARRIOR,
		"damage_multiplier": 3.0,
		"mana_cost": 35,
		"cooldown": 15.0,
		"range": 50.0,
		"aoe_radius": 80.0,
		"hits": 1,
		"hotkey": "skill_4",
		"icon_color": Color(0.7, 0.2, 0.0),
	},
	# === MAGE SKILLS ===
	"fireball": {
		"name": "Fireball",
		"description": "Launch a fireball at enemies.",
		"class": ClassData.ClassType.MAGE,
		"damage_multiplier": 1.8,
		"mana_cost": 10,
		"cooldown": 1.0,
		"range": 150.0,
		"aoe_radius": 30.0,
		"hits": 1,
		"hotkey": "skill_1",
		"icon_color": Color(1, 0.4, 0.0),
	},
	"blizzard": {
		"name": "Blizzard",
		"description": "Ice storm hitting all enemies in a large area.",
		"class": ClassData.ClassType.MAGE,
		"damage_multiplier": 1.3,
		"mana_cost": 25,
		"cooldown": 6.0,
		"range": 120.0,
		"aoe_radius": 100.0,
		"hits": 4,
		"hotkey": "skill_2",
		"icon_color": Color(0.4, 0.7, 1.0),
	},
	"lightning_chain": {
		"name": "Lightning Chain",
		"description": "Lightning bounces between up to 5 enemies.",
		"class": ClassData.ClassType.MAGE,
		"damage_multiplier": 1.5,
		"mana_cost": 20,
		"cooldown": 5.0,
		"range": 130.0,
		"aoe_radius": 80.0,
		"hits": 5,
		"hotkey": "skill_3",
		"icon_color": Color(0.9, 0.9, 0.3),
	},
	"meteor": {
		"name": "Meteor",
		"description": "Call down a meteor for devastating AoE damage.",
		"class": ClassData.ClassType.MAGE,
		"damage_multiplier": 4.0,
		"mana_cost": 45,
		"cooldown": 20.0,
		"range": 140.0,
		"aoe_radius": 120.0,
		"hits": 1,
		"hotkey": "skill_4",
		"icon_color": Color(1, 0.2, 0.0),
	},
	# === RANGER SKILLS ===
	"arrow_shot": {
		"name": "Arrow Shot",
		"description": "Fire a quick arrow at the nearest enemy.",
		"class": ClassData.ClassType.RANGER,
		"damage_multiplier": 1.4,
		"mana_cost": 5,
		"cooldown": 0.6,
		"range": 180.0,
		"aoe_radius": 0.0,
		"hits": 1,
		"hotkey": "skill_1",
		"icon_color": Color(0.3, 0.9, 0.3),
	},
	"multishot": {
		"name": "Multishot",
		"description": "Fire arrows in a cone, hitting multiple enemies.",
		"class": ClassData.ClassType.RANGER,
		"damage_multiplier": 1.0,
		"mana_cost": 15,
		"cooldown": 3.0,
		"range": 160.0,
		"aoe_radius": 70.0,
		"hits": 5,
		"hotkey": "skill_2",
		"icon_color": Color(0.2, 0.8, 0.5),
	},
	"evasive_shot": {
		"name": "Evasive Shot",
		"description": "Dash backward while firing. Grants brief invincibility.",
		"class": ClassData.ClassType.RANGER,
		"damage_multiplier": 1.6,
		"mana_cost": 20,
		"cooldown": 7.0,
		"range": 140.0,
		"aoe_radius": 0.0,
		"hits": 1,
		"hotkey": "skill_3",
		"icon_color": Color(0.5, 1.0, 0.8),
	},
	"rain_of_arrows": {
		"name": "Rain of Arrows",
		"description": "Arrows rain from the sky over a huge area.",
		"class": ClassData.ClassType.RANGER,
		"damage_multiplier": 2.5,
		"mana_cost": 35,
		"cooldown": 14.0,
		"range": 200.0,
		"aoe_radius": 110.0,
		"hits": 6,
		"hotkey": "skill_4",
		"icon_color": Color(0.1, 0.6, 0.2),
	},
}

static func get_skill(skill_id: String) -> Dictionary:
	return SKILLS.get(skill_id, {})

static func get_class_skills(class_type: ClassData.ClassType) -> Array[String]:
	var result: Array[String] = []
	for skill_id in SKILLS:
		if SKILLS[skill_id]["class"] == class_type:
			result.append(skill_id)
	return result
